# Generated by Django 5.2 on 2025-05-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obshaga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='id',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
