# Generated by Django 5.2 on 2025-05-20 10:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obshaga', '0002_remove_rooms_id_alter_rooms_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor', models.CharField(max_length=11)),
                ('value', models.FloatField()),
                ('message', models.TextField()),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obshaga.rooms')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature', models.FloatField()),
                ('oxygen', models.FloatField()),
                ('noise', models.FloatField()),
                ('people', models.PositiveIntegerField()),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obshaga.rooms')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='TopViolators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obshaga.rooms')),
            ],
            options={
                'ordering': ['-quantity'],
            },
        ),
    ]
