# Generated by Django 5.2 on 2025-05-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obshaga', '0003_alert_sensors_topviolators'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='number',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='number',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='topviolators',
            old_name='number',
            new_name='room',
        ),
    ]
