# Generated by Django 5.2 on 2025-05-20 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obshaga', '0004_rename_number_alert_room_rename_number_sensors_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topviolators',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='obshaga.rooms'),
        ),
    ]
