# Generated by Django 5.2 on 2025-05-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obshaga', '0005_alter_topviolators_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
